version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/log/postgresql/data
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: asdasd
  backend:
    build: ./backend/RSMS
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db